// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/collection-view', 'views/entry-view', 'text!templates/entries.hbs'], function(CollectionView, EntryView, template) {
  'use strict';
  var EntriesView;
  return EntriesView = (function(_super) {
    __extends(EntriesView, _super);

    function EntriesView() {
      return EntriesView.__super__.constructor.apply(this, arguments);
    }

    EntriesView.prototype.autoRender = true;

    EntriesView.prototype.tagName = 'ul';

    EntriesView.prototype.id = 'entries-container';

    EntriesView.prototype.itemView = EntryView;

    EntriesView.prototype.template = template;

    template = null;

    return EntriesView;

  })(CollectionView);
});
