<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $vars['meta']['title']; ?></title>
	<meta name="keywords" content=""/>
	<meta name="description" content=""/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="copyright" content=""/>
	<meta name="Author-Corporate" content="Vitaliy Malyshev"/>
	<meta name="Publisher-Email" content="vitfollower@gmail.com"/>
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
	<?php echo $vars['styles']; ?>
	<?php echo $vars['scripts']; ?>
</head>
<body>
<div class="container">

	<?php include(SITE_PATH . 'includes/tpl/header.php'); ?>

	<?php if ($this->authorized()) { ?>
		<div id="content">
			<?php echo $vars['content']; ?>
		</div>
		<div class="clear"></div>

		<div id="footer">
		</div>

	<?php } ?>
</div>
</body>
</html>
