<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
        <title><?php echo $vars['meta']['title'];?></title>
		<meta name="keywords" content="" />
		<meta name="description" content="" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="copyright" content="" />
		<meta name="Author-Corporate" content="Vitaliy Malyshev" />
		<meta name="Publisher-Email" content="vitfollower@gmail.com" />
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <?php echo $vars['styles']; ?>
        <?php echo $vars['scripts']; //?>
	</head>
<body>
<div id="container">

	<?php include(SITE_PATH.'includes/tpl/header.php'); ?>

</div>
</body>
</html>