<?php include(SITE_PATH.'includes/tpl/add_new.php'); ?>

			<div id="week">
			<h2><?=$vars['thisMonthName'];?></h2>
				<p class="itog plus">Получено: <span><?=(int)$vars['getThisMonth'];?> грн.</span></p>
				<p class="itog">&nbsp;&nbsp;/&nbsp;&nbsp;</p>
				<p class="itog minus">Потрачено: <span><?=(int)$vars['spentThisMonth'];?> грн.</span></p>
				<div class="clear"></div>
				<?php if (!$vars['archive']) { ?>
					<p class="itog">(лучший месяц: <?=$vars['best']['sum'];?> грн.)</p>
					</br>
				<?php } ?>
				</br>
				<table class="table" width="100%" cellpadding="0" cellspacing="0">
					<thead>
					<tr class="thead">
						<th width="10%">Тип</th>
						<th width="15%">Дата</th>
						<th width="20%">Название</th>
						<th width="20%">Категория</th>
						<th width="15%">Сумма</th>
						<th width="16%"></th>
					</tr>
				</thead>
				<tbody>
				<?php
					foreach ($vars['thismonth'] as $row)
					{
						if($row['d']=='-') $icon = '<img src="/images/minus.png" alt="" />';
						elseif($row['d']=='+') $icon = '<img src="/images/plus.png" alt="" />';
						echo '<tr id="tr-'.$row['id'].'" num="'.$row['id'].'">
								<td class="icon-edit">'.$icon.'</td>
								<td class="date-edit">'.$this->date_view($row['date'], "dd.mm.YY").'</td>
								<td class="name-edit">'.$row['name'].'</td>
								<td class="type-edit">'.$row['type'].'</td>
								<td class="sum-edit">'.$row['sum'].' ₴</td>
								<td>
									<a class="label label-primary" href="javascript:void(0);" onclick="editEntry('.$row['id'].');">редактировать</a>
									<a class="label label-danger" href="javascript:void(0);" onclick="deleteEntry('.$row['id'].');">удалить</a>
								</td>
							</tr>';

						//EDIT ENTRY
						echo '<tr id="tr-'.$row['id'].'-edit" num="'.$row['id'].'" class="edit-row hidden">
								<td>&nbsp;</td>
								<td><input type="text" class="datepicker form-control input-sm" id="date-edit-'.$row['id'].'" value="'.$this->date_view($row['date'], "dd.mm.YY").'" /></td>
								<td><input type="text" class="form-control input-sm" id="name-edit-'.$row['id'].'" value="'.$row['name'].'" /></td>
								<td><select name="types" class="form-control input-sm" id="types-edit-'.$row['id'].'">';
						foreach($vars['typesArray'] as $type) {
							$sel = '';
							if($type['name']==$row['type']) $sel='selected="selected"';
							echo '<option value='.$type['id'].' '.$sel.'>'.$type['name'].'</option>';
						}
						echo '</select>';
						echo '</td>
								<td><input type="text" class="form-control input-sm" id="sum-edit-'.$row['id'].'" value="'.$row['sum'].'"/></td>
								<td class="links">
									<a class="label label-success" href="javascript:void(0);" onclick="saveEntry('.$row['id'].');">сохранить</a>
									<a class="label label-danger" href="javascript:void(0);" onclick="editEntry('.$row['id'].');">отмена</a>
								</td>
							</tr>';
					}
				?>
			</tbody>
		</table>
			</div>

			<div id="statistics">

				<h2>Расходы</h2>

				<script type="text/javascript" src="../../js/follower.xcharts.js"></script>
				<script language="javascript" type="text/javascript">
					$(document).ready( function () {
					var data = {
						<?php
							$first =  true;
							foreach ($vars['catstats'] as $row) {
								if(!$first) echo ',';
								echo  "'".$row['catname']."': ".$row['sum']."";
								$first = false;
							}
						?>
					};
					$('#category-statistic').xcharts({data: data, type: 'linear', height: 10 });
					});
				</script>

				<div id="category-statistic"></div>

				<h2>Статистика</h2>

				<script language="javascript" type="text/javascript">
					$(document).ready( function() {
								var spent = <?=$vars['statSpentJSON'];?>;
								var got = <?=$vars['statGotJSON'];?>;

								var data = [
									{ data: spent, label: "Потрачено" },
									{ data: got, label: "Получено" }
								];

								var options = {
									canvas: true,
									xaxes: [ { mode: "time" } ],
									legend: { position: "nw" }
								}

								$.plot("#graphic-statistic", data, options);

					});
				</script>

				<div id="graphic-statistic"></div>

				<h2>Архив</h2>

				<div class="row">
				<?php
					$year = 0;
					$theader = '<table class="table">
									<thead>
										<tr class="thead">
											<th>Месяц</th>
											<th>Потрачено</th>
											<th>Получено</th>
											<th>Накоплено</th>
										</tr>
									</thead>
									<tbody>';

					for ($i = 0; $i < count($vars['statSpent']); $i++)
					{
						$year_row = $vars['statSpent'][$i]['year'];

						if($year_row != $year)
						{
							if($year!=0)
							{
								echo '</tbody>
								</table></div>';
							}

							echo '<div class="year-table">
								<h4>'.$year_row.' <span>(-'.(int)$vars['statSpentYear'][$year_row].' / +'.(int)$vars['statGotYear'][$year_row].')</span></h4>' . $theader;

							$year = $year_row;
						}

						$month = (int)$vars['statSpent'][$i]['month'];
						$year = (int)$vars['statSpent'][$i]['year'];
						echo '<tr>
								<td><a href="/?month='.$month.'&year='.$year.'">'.$this->getMonth($month).'<a/></td>
								<td>';

								echo $vars['statSpent'][$i]['sum'];
								echo '</td><td>';
								echo $vars['statGot'][$i]['sum'];

								echo '</td><td>';
								echo $vars['statGot'][$i]['sum'] - $vars['statSpent'][$i]['sum'];

								echo '</td>
							</tr>';

					}
					echo '</table>';
				?>
				</div>
			</div>
