<div class="panel panel-default">
	<div class="panel-heading">Редактировать профиль</div>
	<div class="panel-body">
		<form method="post" class="form-horizontal">
			<div class="col-xs-12">
				<div class="form-group">
					<label class="control-label">Имя: </label>
					<input class="form-control" type="text" name="name" value="<?php echo $vars['user']['name']; ?>" />
				</div>
				<div class="form-group">
					<label>Логин: </label>
					<input class="form-control" type="text" name="login" value="<?php echo $vars['user']['login']; ?>" />
				</div>
				<div class="form-group">
					<label class="control-label">Пароль: </label>
					<input class="form-control" type="text" name="password" value="">
				</div>

				<div class="form-group">
					<label class="control-label">Категории: </label>
				</div>

					<?php
						foreach ($vars['categories'] as $row) {

							$check = '';
							foreach ($vars['my_categories'] as $row2) {
								if($row['id']==$row2['id']) {
									$check = 'checked="checked"';
									break;
								}
							}
							
							echo '<div class="checkbox">
									<label for="c-'.$row['id'].'">
									<input type="checkbox" '.$check.' name="categories[]" value="'.$row['id'].'" id="c-'.$row['id'].'"> '.$row['name'].'
									</label>
								</div>';
						}
					?>
					<br/>

					<?php
						if(isset($vars['message'])) echo $vars['message'];
					?>

					<div class="form-group">
						<input type="submit" class="btn btn-default" name="save" value="Сохранить" />
					</div>
					<div class="form-group">
						<a href="/exportxls">Экспорт в Excel</a>
					</div>
			</form>
		</div>
	</div>
</div>