<ul class="nav navbar-nav navbar-right">
	<form method="post" action="/login" class="form-inline" role="form" style="margin-top: 7px;">
		<div class="form-group">
			<input type="text" class="form-control" name="name" placeholder="Логин">
		</div>
		<div class="form-group">
			<input type="password" class="form-control" name="pass" placeholder="Пароль">
		</div>
		<button type="submit" class="btn btn-default">Войти</button>
	</form>
</ul>