<div id="category-view">
	<h2><?php echo $vars['catname']; ?></h2>

	<div id="pie"></div>
</div>

<script language="javascript" type="text/javascript">
	$(document).ready( function() {
		var spent = <?=$vars['piedata'];?>;

		var data = [
			{ data: spent, label: "Итог" },
		];

		var options = {
			canvas: true,
			xaxes: [ { mode: "time" } ],
			legend: { position: "nw" }
		}

		$.plot("#pie", data, options);

		});
</script>