<table class="table main-table" width="100%" cellpadding="0" cellspacing="0">
			<thead>
			<tr class="thead">
				<th width="10%">Тип</th>
				<th width="15%">Дата</th>
				<th width="20%">Название</th>
				<th class="cat-row" width="20%">Категория</th>
				<th width="15%">Сумма</th>
				<th width="16%"></th>
			</tr>
		</thead>
		<tbody>
			<?php
				foreach ($vars['entries'] as $row) {
					if($row['category']['type']=='-') $icon = '<img src="/public/images/minus.png" alt="" />';
					elseif($row['category']['type']=='+') $icon = '<img src="/public/images/plus.png" alt="" />';
					echo '<tr id="tr-'.$row['id'].'" num="'.$row['id'].'">
							<td class="icon-edit">'.$icon.'</td>
							<td class="date-edit">'.date("d.m.Y", strtotime($row['date'])).'</td>
							<td class="name-edit">'.$row['name'].'</td>
							<td class="cat-row type-edit">'.$row['category']['name'].'</td>
							<td class="sum-edit">'.$row['sum'].' ₴</td>
							<td>
								<a class="label label-primary" href="javascript:void(0);" onclick="editEntry('.$row['id'].');">редактировать</a>
								<a class="label label-danger" href="javascript:void(0);" onclick="deleteEntry('.$row['id'].');">удалить</a>
							</td>
						</tr>';

					//EDIT ENTRY
					echo '<tr id="tr-'.$row['id'].'-edit" num="'.$row['id'].'" class="edit-row hidden">
							<td>&nbsp;</td>
							<td><input type="text" class="datepicker form-control input-sm" id="date-edit-'.$row['id'].'" value="'.date("d.m.Y", strtotime($row['date'])).'" /></td>
							<td><input type="text" class="form-control input-sm" id="name-edit-'.$row['id'].'" value="'.$row['name'].'" /></td>
							<td><select name="types" class="form-control input-sm" id="types-edit-'.$row['id'].'">';
					foreach($vars['categories'] as $id => $type) {
						$sel = '';
						if($id==$row['category']['id']) $sel='selected="selected"';
						echo '<option value='.$id.' '.$sel.'>'.$type.'</option>';
					}
					echo '</select>';
					echo '</td>
							<td><input type="text" class="form-control input-sm" id="sum-edit-'.$row['id'].'" value="'.$row['sum'].'"/></td>
							<td class="links">
								<a class="label label-success" href="javascript:void(0);" onclick="saveEntry('.$row['id'].');">сохранить</a>
								<a class="label label-danger" href="javascript:void(0);" onclick="editEntry('.$row['id'].');">отмена</a>
							</td>
						</tr>';
				}
			?>
		</tbody>
	</table>