<?php echo $vars['new_entry']; ?>

<div id="week">
	<h2><?=$vars['archiveDate'];?></h2>
		<p class="itog plus">Получено: <span><?=(int)$vars['getThisMonth'];?> грн.</span></p>
		<p class="itog">&nbsp;&nbsp;/&nbsp;&nbsp;</p>
		<p class="itog minus">Потрачено: <span><?=(int)$vars['spentThisMonth'];?> грн.</span></p>
		<div class="clear"></div>
		<?php if (!$vars['archiveDate']) { ?>
			<p class="itog">(лучший месяц: <?=$vars['best']['sum'];?> грн.)</p>
			</br>
		<?php } ?>
		</br>
		<?php echo $vars['entries_table']; ?>
</div>

	<div id="statistics">

		<h2>Расходы</h2>
		<script language="javascript" type="text/javascript">
			$(document).ready( function () {
				var data = { <?php
								$first =  true;
								foreach ($vars['catstats'] as $row) {
									if(!$first) echo ',';
									echo  "'".$row['catname']."': ".$row['sum']."";
									$first = false;
								}
							?> };
				$('#category-statistic').xcharts({data: data, type: 'linear', height: 10 });
			});
		</script>

		<div id="category-statistic"></div>

		<h2>Статистика</h2>

		<script language="javascript" type="text/javascript">
			$(document).ready( function() {
						var spent = <?=$vars['statSpentJSON'];?>;
						var got = <?=$vars['statGotJSON'];?>;

						var data = [
							{ data: spent, label: "Потрачено" },
							{ data: got, label: "Получено" }
						];

						var options = {
							canvas: true,
							xaxes: [ { mode: "time" } ],
							legend: { position: "nw" }
						}

						$.plot("#graphic-statistic", data, options);

			});
		</script>

		<div id="graphic-statistic"></div>

		<h2>Архив</h2>

		<div class="row">
		<?php
			$year = 0;
			$theader = '<table class="table">
							<thead>
								<tr class="thead">
									<th>Месяц</th>
									<th>Потрачено</th>
									<th>Получено</th>
									<th>Накоплено</th>
								</tr>
							</thead>
							<tbody>';

			for ($i = 0; $i < count($vars['statSpent']); $i++)
			{
				$year_row = $vars['statSpent'][$i]['year'];

				if($year_row != $year)
				{
					if($year!=0)
					{
						echo '</tbody>
						</table></div>';
					}

					echo '<div class="year-table">
						<h4>'.$year_row.' <span>(-'.(int)$vars['statSpentYear'][$year_row].' / +'.(int)$vars['statGotYear'][$year_row].')</span></h4>' . $theader;

					$year = $year_row;
				}

				$month = (int)$vars['statSpent'][$i]['month'];
				$year = (int)$vars['statSpent'][$i]['year'];
				echo '<tr>
						<td><a href="/?month='.$month.'&year='.$year.'">'.$vars['statSpent'][$i]['monthName'].'<a/></td>
						<td>';

						echo $vars['statSpent'][$i]['sum'];
						echo '</td><td>';
						echo $vars['statGot'][$i]['sum'];

						echo '</td><td>';
						echo $vars['statGot'][$i]['sum'] - $vars['statSpent'][$i]['sum'];

						echo '</td>
					</tr>';

			}
			echo '</table>';
		?>
		</div>
	</div>
