<div class="panel panel-default">
	<div class="panel-heading">Новая запись</div>
	<div class="panel-body add-new-form">
		<form class="form-inline row" role="form" method="post" action="/add" autocomplete="off">
			<div class="form-group col-xs-2">
				<input type="text" class="datepicker form-control" id="date-add" name="date" value="<?=date("d.m.Y");?>" placeholder="Когда ?" />
			</div>
			<div class="form-group col-xs-3">
				<input type="text" class="form-control" name="name" value="" placeholder="Что ?" />
			</div>
			<div class="form-group col-xs-2">
				<input type="text" class="form-control" name="amount" value="" placeholder="Сколько ?"/>
			</div>
			<div class="form-group col-xs-2">
				<?php echo $this->select($vars['categories'], ['name' => 'types', 'class' => 'form-control']); ?>
			</div>
			<div class="form-group col-xs-2">
				<button type="submit" class="btn btn-default" name="AddNew">Добавить</button>
			</div>
		</form>
	</div>
</div>