// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'models/entry', 'text!templates/entry.hbs'], function(View, Entry, template) {
  'use strict';
  var EntryView;
  return EntryView = (function(_super) {
    __extends(EntryView, _super);

    function EntryView() {
      return EntryView.__super__.constructor.apply(this, arguments);
    }

    EntryView.prototype.autoRender = true;

    EntryView.prototype.tagName = 'li';

    EntryView.prototype.className = 'entry';

    EntryView.prototype.template = template;

    template = null;

    return EntryView;

  })(View);
});
