<?php include(SITE_PATH.'includes/tpl/add_new.php'); ?>

    		<?php if(!$vars['archive']) { ?>
		    <div id="week">
		    <h2>За последнюю неделю</h2>

		    	<table class="table" width="100%" cellpadding="0" cellspacing="0">
		    		<thead>
			    		<tr class="thead">
			    			<th width="10%">Тип</th>
			    			<th width="20%">Дата</th>
			    			<th width="25%">Название</th>
			    			<th width="20%">Категория</th>
			    			<th width="15%">Сумма</th>
			    			<th width="10%"></th>
			    		</tr>
			    	</thead>
			    	<tbody>
			    	<?
			    		foreach ($vars['lastweek'] as $row) 
			    		{
			    			if($row['d']=='-') $icon = '<img src="/images/minus.png" alt="" />';
			    			elseif($row['d']=='+') $icon = '<img src="/images/plus.png" alt="" />';
			    			echo '<tr id="tr-'.$row['id'].'" num="'.$row['id'].'">
			    				<td>'.$icon.'</td>
			    				<td>'.$this->date_view($row['date'], "dd.mm.YY").'</td>
			    				<td>'.$row['name'].'</td>
			    				<td>'.$row['type'].'</td>
			    				<td>'.$row['sum'].' ₴</td>
			    				<td><a href="javascript:void(0);" onclick="deleteEntry('.$row['id'].');">удалить</a></th>
			    			</tr>';
			    		}
			    	?>
				    </tbody>
				</table>
		    </div>

			<?php include(SITE_PATH.'includes/tpl/best_month.php'); ?>

		    <?php } ?>

		    <div id="week">
		    <h2><?=$vars['thisMonthName'];?></h2>
		    	<p class="itog plus">Получено: <span><?=(int)$vars['getThisMonth'];?> грн.</span></p>
		    	<p class="itog minus">Потрачено: <span><?=(int)$vars['spentThisMonth'];?> грн.</span></p>
		    	<br/>
		    	<table class="table" width="100%" cellpadding="0" cellspacing="0">
		    		<thead>
		    		<tr class="thead">
		    			<th width="10%">Тип</th>
		    			<th width="20%">Дата</th>
		    			<th width="25%">Название</th>
		    			<th width="20%">Категория</th>
		    			<th width="15%">Сумма</th>
		    			<th width="10%"></th>
		    		</tr>
		    	</thead>
		    	<tbody>
		    	<?
		    		foreach ($vars['thismonth'] as $row) 
		    		{
		    			if($row['d']=='-') $icon = '<img src="/images/minus.png" alt="" />';
		    			elseif($row['d']=='+') $icon = '<img src="/images/plus.png" alt="" />';
		    			echo '<tr id="tr-'.$row['id'].'" num="'.$row['id'].'">
		    				<td>'.$icon.'</td>
		    				<td>'.$this->date_view($row['date'], "dd.mm.YY").'</td>
		    				<td>'.$row['name'].'</td>
		    				<td><a href="/category/'.$row['category_id'].'?month='.$this->date_view($row['date'], "mm").'&year='.$this->date_view($row['date'], "YY").'">'.$row['type'].'</a></td>
		    				<td>'.$row['sum'].' ₴</td>
		    				<td><a href="javascript:void(0);" onclick="deleteEntry('.$row['id'].');">удалить</a></th>
		    			</tr>';
		    		}
		    	?>
		    </tbody>
		</table>
		    </div>

		    <div id="statistics">

		    	<h2>Расходы</h2>

		    	<script language="javascript" type="text/javascript">
		    		$(document).ready( function() {
		    			var data = [
				    			<?php
				    					foreach ($vars['catstats'] as $row) {
				    						echo  '{ label: "'.$row['catname'].'", data: '.$row['sum'].' },';
				    					}
				    			?>
							];
							$.plot('#category-statistic', data, {
							    series: {
							        pie: {
							            show: true,
							            label: {
						                    show: true,
						                    radius: 1,
						                    formatter: function(label, series){
						                    	var sum = String(series.data);
						                    	sum = sum.substring(2, sum.length);

						                        return '<div style="font-size:8pt;text-align:center;padding:2px;color:white;">'+label+'<br/>'+sum+' грн. <br/>'+Math.round(series.percent)+'%</div>';
						                    },
						                    background: { opacity: 0.7 }
						                }
							        }
							    }
							});
												});
									    	</script>

		    	<div id="category-statistic"></div>


		    	<h2>Статистика</h2>

		    	<script language="javascript" type="text/javascript">
		    		$(document).ready( function() {
								var spent = <?=$vars['statSpentJSON'];?>;
								var got = <?=$vars['statGotJSON'];?>;

								var data = [
									{ data: spent, label: "Потрачено" },
									{ data: got, label: "Получено" }
								];

								var options = {
									canvas: true,
									xaxes: [ { mode: "time" } ],
									legend: { position: "nw" }
								}

								$.plot("#graphic-statistic", data, options);

					});
		    	</script>

		    	<div id="graphic-statistic"></div>

		    	

		    	<h2>Архив</h2>

		    	<? 
		    		$year = 0;			    	
			    	$theader = '<table class="table">
			    					<thead>
						    			<tr class="thead">
						    				<th>Месяц</th>
						    				<th>Потрачено</th>
						    				<th>Получено</th>
						    				<th>Накоплено</th>
						    			</tr>
					    			</thead>
					    			<tbody>';

	    			for ($i = 0; $i < count($vars['statSpent']); $i++) 
	    			{
	    				$year_row = $vars['statSpent'][$i]['year'];

	    				if($year_row != $year) 
	    				{
	    					if($year!=0) 
    						{
    							echo '</tbody>
    							</table></div>';
    						}

	    					echo '<div class="year-table">
	    						<h4>'.$year_row.'</h4>' . $theader;

	    					$year = $year_row;
	    				}

	    				$month = (int)$vars['statSpent'][$i]['month'];
	    				$year = (int)$vars['statSpent'][$i]['year'];
	    				echo '<tr>
		    					<td><a href="/?month='.$month.'&year='.$year.'">'.$this->getMonth($month).'<a/></td>
		    					<td>';

		    					echo $vars['statSpent'][$i]['sum'];
		    					echo '</td><td>';
		    					echo $vars['statGot'][$i]['sum'];

		    					echo '</td><td>';
		    					echo $vars['statGot'][$i]['sum'] - $vars['statSpent'][$i]['sum'];

		    					echo '</td>
	    					  </tr>';
	    			}
		    	?>
		    	</table>
		    </div>
