
<div id="profile">
	<h2>Редактировать профиль</h2>
<form method="post">
	<fieldset>
		<h5>Личные данные:</h5>
		<label>Имя: </label>
		<input type="text" name="name" value="<?php echo $vars['user']['name']; ?>" /> <br/><br/>
		<label>Логин: </label>
		<input type="text" name="login" value="<?php echo $vars['user']['login']; ?>" /> <br/>
		<label>Пароль: </label>
		<input type="text" name="password" value="">
		<br/>
	</fieldset>

	<fieldset class="categories">
		<h5>Категории:</h5>
		<?php
			foreach ($vars['categories'] as $row) {

				$check = '';
				foreach ($vars['my_categories'] as $row2) {
					if($row['id']==$row2['id']) {
						$check = 'checked="checked"';
						break;
					}
				}
				
				echo '<input type="checkbox" '.$check.' name="categories[]" value="'.$row['id'].'" id="c-'.$row['id'].'"> <label for="c-'.$row['id'].'">'.$row['name'].'<label><br/>';
			}
		?>
		<br/>
	</fieldset>

	<?php
		if(isset($vars['message'])) echo $vars['message'];
	?>

	<input type="submit" class="btn btn-default" name="save" value="Сохранить" />
</form>

	<a href="/exportxls">Экспорт в Excel</a>
</div>