// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var Entry;
  return Entry = (function(_super) {
    __extends(Entry, _super);

    function Entry() {
      return Entry.__super__.constructor.apply(this, arguments);
    }

    Entry.prototype.url = function() {
      if (this.isNew) {
        return 'http://myacc.bl.ee/api/entry/action/view/id/' + this.id;
      } else {
        return 'http://myacc.bl.ee/api/entry/action/view/id/id/' + this.id;
      }
    };

    return Entry;

  })(Model);
});
