// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/entry', 'models/base/collection'], function(Chaplin, Entry, Collection) {
  'use strict';
  var Entries;
  return Entries = (function(_super) {
    __extends(Entries, _super);

    function Entries() {
      return Entries.__super__.constructor.apply(this, arguments);
    }

    Entries.prototype.model = Entry;

    Entries.prototype.url = 'http://myacc.bl.ee/api/entry/action/list';

    return Entries;

  })(Collection);
});
