// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/model'], function(Model) {
  'use strict';
  var Types;
  return Types = (function(_super) {
    __extends(Types, _super);

    function Types() {
      return Types.__super__.constructor.apply(this, arguments);
    }

    Types.prototype.url = 'http://myacc.bl.ee/api/types/action/list/';

    return Types;

  })(Model);
});
