// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'routes'], function(Chaplin, routes) {
  'use strict';
  var Application;
  return Application = (function(_super) {
    __extends(Application, _super);

    function Application() {
      return Application.__super__.constructor.apply(this, arguments);
    }

    Application.prototype.title = 'Chaplin example application';

    Application.prototype.initMediator = function() {
      Chaplin.mediator.user = null;
      return Application.__super__.initMediator.apply(this, arguments);
    };

    return Application;

  })(Chaplin.Application);
});
