// Generated by CoffeeScript 1.7.1
define(function() {
  'use strict';
  return function(match) {
    match('', 'entries#home');
    match('entries', 'entries#home');
    match('entries-:date', 'entries#month');
    match('login', 'login#loginpage');
    match('logout', 'login#logout');
    match('profile', 'login#profile');
    match('edit-:id', 'entries#edit');
    match('delete-:id', 'entries#delete');
    return match('add', 'entries#new');
  };
});
